### ISSUE TITLE
Error when trying to run 'bundle exec rake db:setup'

### ISSUE THREAD

**Issue by sam-twee** [sonianand11/simple_store_app#1]
Error is as follows:

```
Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
```

**Comment by sonianand11** [comment]
Yes, config/database.yml has been ignored. So you need to create it in your local machine. I am going to push example database.yml so that it will helpful to you.

**Comment by sonianand11** [comment]
Done, Please find`config/database-example.yml` file in repo and configure it as per your database.
